# Site settings
title: Criminal Procedure Study Guide
email: contact.amyc@pm.me
description: A flowchart-based study guide for Criminal Procedure covering key Fourth, Fifth, and Sixth Amendment doctrines.
baseurl: "" # the subpath of your site (repository name)
url: "" # the base hostname & protocol for your site

# Include CrimProGuide directory in the build
include: ["CrimProGuide"]

# Build settings
markdown: kramdown
highlighter: rouge
keep_files: ["CrimProGuide"]

# Jekyll plugins
plugins:
  - jekyll-last-modified-at # For automatic last updated timestamps

# Collections
collections:
  sections:
    output: true
    permalink: /:collection/:name/

# Default front matter
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "CrimProGuide/sections"
    values:
      layout: "section"
